### ISSUE TITLE
Integrate some changes from https://gist.github.com/cbilson/ae0d90d163be4d769f8a15ddb58292bc

### ISSUE THREAD

**Issue by fpvmorais** [rkiggen/ob-powershell#6]
Hello,

[@cbilson](https://github.com/cbilson) created this gist in 2018 and I've leater added support for variables in the code. My elisp-fu is not great and I'm not sure if this is the right way to do it, but I've been using this since 2019 and has served me well. It seems you have this published in Melpa. Would you be open for a pull request?

**Comment by zzeitt** [comment]
Could you give me an example about how to use var in your provided ob-powershell.el? Because when I tested it with `:var tmp="string"`, I got this error.
![image](https://github.com/user-attachments/assets/9b41429e-81f2-45d3-917d-0bd2c20b0a28)

**Comment by fpvmorais** [comment]
This works for me:
```orgmode 
#+begin_src powershell :var tmp="Hello"

Write-Host $tmp

#+end_src 

#+RESULTS:
: Hello
```

![image](https://github.com/user-attachments/assets/eae4ee56-3531-4641-9ed9-00941e68f653)

**Comment by zzeitt** [comment]
That's weird. What I have done is replacing the melpa version ob-powershell.el with the revised one. Seems like the replacement doesn't take effect.

**Comment by fpvmorais** [comment]
Well you can try to use my fork of the code. This is what I am using:

```emacs-lisp
(use-package ob-powershell
  :straight (ob-powershell.el :type git
                              :repo "https://github.com/fpvmorais/ob-powershell.git";
                              :local-repo "ob-powershell")
  :commands
  (org-babel-execute:powershell
   org-babel-expand-body:powershell))
```

```org-mode
#+begin_src powershell :var tmp="Hello"

Write-Host $tmp

#+end_src 

#+RESULTS:
: Hello
```

**Comment by fpvmorais** [comment]
If you're using Powershell core, you should also check the ob-pwsh (https://github.com/togakangaroo/ob-pwsh)
It also lacks the variable stuff, but I added them on my fork: https://github.com/fpvmorais/ob-pwsh.git

**Comment by zzeitt** [comment]
After manually installing it, it works! Thx!
